org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:\\Users\\Vijay Jha\\AppData\\Local\\Programs\\Eclipse Adoptium\\jdk-17.0.18.8-hotspot\\
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
org.gradle.caching=false
